# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a0a2eb70e237396e30e0f2681103b3084ba3dda48e64401e75b267fb6091ba4c31ae24a025af3f7777bdee88fa64f9bf7e2e8cdd0850bcab103b5716285cbbe

test:
  secret_key_base: ecbd9850d4e51857cda3313b3be810b0ab85f51b9f6b0a67e8ea360ca9a41fe753c567c44a1e01d54654413378fb534a91f08dc8bb861655b796912da3386e09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
